### PR TITLE
TinyChat support for GQA and memory efficient loading

### PR DESCRIPTION
**Pull request by kentang-mit**
Add implementation from @ys-2020 that allows deployment of LLaMA-2-70B models on Orin-64G. Also add a faster context stage implementation compared with the release last week.

### CODE REVIEW

**Comment by casper-hansen** [comment]
Is it correctly understood that AWQ now solely uses the modified GEMM kernel for processing context? Also, is the modified GEMM kernel faster than the previous one?

**Comment by kentang-mit** [comment]
Hi Casper,

AWQ solely uses the GEMM kernel for context processing. I think its speed is on-par with the previous version, but it has been adapted to work with the latest weight packing scheme.

Best,
Haotian

**Comment by casper-hansen** [comment]
> Hi Casper,
> 
> AWQ solely uses the GEMM kernel for context processing. I think its speed is on-par with the previous version, but it has been adapted to work with the latest weight packing scheme.
> 
> Best, Haotian

Hi Haotian, thank you for answering! I have tested the new GEMM kernel. It is a good improvement over GEMV. It is 2x faster than GEMV but 5-6x slower than the original GEMM kernel. 

Speed of context:
- GEMM (original): 2400 tokens/s on 7B
- GEMM (new): 440 tokens/s on 7B

**Comment by kentang-mit** [comment]
Interesting. Is that just for the context stage? We haven't done any formal benchmark yet, but we will definitely work on further improve the speed of this kernel.

**Comment by casper-hansen** [comment]
> Interesting. Is that just for the context stage? We haven't done any formal benchmark yet, but we will definitely work on further improve the speed of this kernel.

Yes, this is only for the context stage. 

Let me say this. In general, the new GEMV kernel is 20% faster at token generation than the original GEMM kernel. The only problem is that the context stage can be slow if you want to use 4-8-16k contexts.

**Comment by Pyroserenus** [comment]
I'd like to confirm that with preliminary testing of small batch, high context loads on TGI AWQ (4k context, 3090, 13b, ~16k max batch size) that AWQ seems to be underperforming vs even autogptq. It could be a flaw in my testing methodology and I'll be doing more tests tonight.

**Review by Sakits — APPROVED** [review]
Looks good to me.

**Pull request merged**
